[package]
name = "hyoubkp_tokmap_rule"
version = "0.1.0"
edition = "2021"

[features]
user = []

[dependencies]
hyoubkp_base = { path = "../hyoubkp_base", features = [ "toml" ] }
serde = { workspace = true }
toml = { workspace = true }